# Generated by Django 3.2.9 on 2021-11-18 15:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='user.png', upload_to=users.models.img_uploader, verbose_name='Foto'),
        ),
    ]
