# Generated by Django 3.2.9 on 2021-11-17 22:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el tablero', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('status', models.CharField(blank=True, choices=[('o', 'Público'), ('p', 'Privado')], default='p', help_text='Visibilidad del tablero', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('content', models.TextField(max_length=500, verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='notes.board', verbose_name='Tablero')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['-created_at'],
            },
        ),
    ]
