# Generated by Django 3.2.9 on 2021-11-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para el tablero', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.board', verbose_name='Tablero'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
