# Generated by Django 3.2.9 on 2021-11-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20211118_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideas',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(blank=True, choices=[('publico', 'Público'), ('privado', 'Privado')], default='privado', help_text='Visibilidad del tablero', max_length=7, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última módificación'),
        ),
    ]
