# Generated by Django 3.2.9 on 2021-11-11 22:16

import Practica_AIATIC.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('username', models.CharField(max_length=28, unique=True, verbose_name='Usuario')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('id_num', models.CharField(max_length=12, unique=True, verbose_name='Número de identificación')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último logueo')),
                ('profile_picture', models.ImageField(blank=True, default='user.png', upload_to=Practica_AIATIC.models.img_uploader, verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personal')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', Practica_AIATIC.models.UserManager()),
            ],
        ),
    ]
